"""First test migration

Revision ID: 37dedff75b2d
Revises: 
Create Date: 2023-11-07 14:52:38.566465+00:00

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37dedff75b2d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('test_migration', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'test_migration')
    # ### end Alembic commands ###
